steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-eurocoins:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/my-eurocoins:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'my-eurocoins'
    - '--image'
    - 'gcr.io/$PROJECT_ID/my-eurocoins:$COMMIT_SHA'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--memory'
    - '512Mi'
    - '--cpu'
    - '1'
    - '--max-instances'
    - '10'
    - '--min-instances'
    - '0'
    - '--port'
    - '8000'
    - '--set-env-vars'
    - 'APP_ENV=production,GOOGLE_CLOUD_PROJECT=$PROJECT_ID'

images:
  - gcr.io/$PROJECT_ID/my-eurocoins:$COMMIT_SHA

timeout: '1200s'
